# From: https://raw.githubusercontent.com/commercialhaskell/stack/stable/doc/travis-simple.yml
# https://docs.haskellstack.org/en/stable/travis_ci/

# Choose a build environment
dist: bionic

# Do not choose a language; we provide our own build tools.
language: generic

services: docker

# Caching so the next build will be fast too.
cache:
  directories:
    - "$HOME/.stack"

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  # Build dependencies
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  - stack build --copy-bins --local-bin-path . || travis_terminate 1
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" . || travis_terminate 1

before_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master

env:
  global:
  - IMAGE_NAME=l7r7/gitlab-ci-build-statuses
  - secure: Vr2xOYxrXR+eEisAMU9Ke8ZFCIe0S8hFK0HKRD+E3YgD4PraurKbFSr0G48t9Heu6cNWJAagliv4Q2GTuI7fGn7Hod7lBe50FDPhhB7je0qjxE0Hee+S/vaNayGCa/WWdgd6NcYGhfD7XYnRtYc1d0Jg+7395IFK41NJ3WwHaDAIqqhWy/udNMxwAol09RwUVyoff4T4s+gZBnAhvfnf1OQmyTpazEB4jjY5LlLWnKmN/M98moVe96qEBusXd2XHNTLZQiVkdkcJXjr3V5W/a7fcLFG8J5KOmDQ0GiMorh3itdtLnXaqoznUT+aT7/GJOX5wkVx+Lur2G92KOfiPUXgA4h10AxmD1n4HwOTtazxEesA0u0mhnd6YPQf+3rbRehBUC6wJ5dN2ndUOa5626cr3ZHQEcvv6f50ZTCX/LuivKwVOgS+DCkjKlkqzzNn4+J1/HYsbEuEXWC6b06/9pRFdIFFDbRehdUnJ3yXhQqgjqOsMRSc7PZMHMhf2yE3fecLpyE+feaaNaT3OEJjgYTRqdPQE54YwBNYFU2sJO6VtVnexJ2cYd5Tkrh0iSUV/9M0YpXj0iAjgPUI/PZ1gXi9ij0Q3TbAupucyyR/YDIjbhrF+uYDWWWOTXZybQqmC0wiM3zjfJKO9ko0gztO8tx6KveJgWAy1bu0+njChbwk=
  - secure: g7myrYGOdbRPnwhRGbKixRBzUTm3aCgWTv3K+gWiFOf2ph34zDHKT+FoZZEYlb37jfMhnC4fiTxEJEp5sa925QWcCmZxVUANo8sb49K3VRDqKycAdsgaEISMksB5DVdMwXEXVzpTExVZHFzRtJinEUi+ANMJd4lbsN/py9VCxswwnTM5KeJqM9n5Byyx0par00o2KLXSqkC1N+Q2Dxa6hx6a2bp0PkIxIDJB0OCsBZICFYbsW/uyvu3sA/kMcvdGFIaPfq6G1kovLQnSbsXCG4C0bGSCSBs1rpSAc5EwLhij2rafGTvkBDIXYVl+ALJqqybDleFiJS7Bp3FhmC4aIrqa9a01I/+HING5mMUlqz72NZbXZXUAGBhXWhj6S+zpCMLgD1JEn3cevsLFV4uEpR0hQweyWmT5eIGMUT6O4wqgUC53iG+QWMvleNt8Tv+Qhjt6zQpm9Sqp2FNbHnWwNxn3w1btg0HKYh/jVZ1X5VvWonrEpOSlH+t4izR/0Ug17GIbVuXtFUidbA2mQobeoDxHyBUkUBy1CghIt9z5kf0ONwNFqRAIPIsFg4QzrWg1CX4fLFLPjUpSgf9F327KlmmtwI7NHP9F0fjEMk7fMhOhRLwCqGPPbREBzy7MEselVa4dfc0Rk5KLUIffCt31juurlBCdqUSYdhLS3TUgj1w=
