name: gitlab-ci-build-statuses
version: "0.1.0.0"
description: Please see the README on GitHub at <https://github.com/l7r7/gitlab-ci-build-statuses#readme>
author: Leonhard Riedisser
maintainer: leo008180@googlemail.com
copyright: 2020 Leonhard Riedisser
license: BSD3
github: l7r7/gitlab-ci-build-statuses
language: GHC2021

extra-source-files:
  - README.md
  - ChangeLog.md

ghc-options:
  - -fwrite-ide-info
  - -hiedir=.hie
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -fhide-source-paths
  - -Wpartial-fields
  - -Wmissing-deriving-strategies
  - -Wunused-packages

dependencies:
  - base >=4.7 && <5

default-extensions:
  - DerivingStrategies
  - StrictData

library:
  source-dirs: src
  default-extensions:
    - NoImplicitPrelude
  ghc-options:
    - -fno-warn-orphans
    - -O2
    - -flate-specialise
    - -fspecialise-aggressively
    - -fplugin=Polysemy.Plugin
    - -Wmissing-export-lists
  dependencies:
    - aeson
    - aeson-casing
    - async
    - barbies
    - bifunctors
    - burrito >=2.0.0.0
    - cache
    - clock
    - containers
    - either
    - extra
    - githash
    - higgledy
    - http-conduit
    - http-link-header
    - http-types
    - katip
    - lens
    - lucid
    - network-uri
    - path
    - polysemy >=1.7
    - polysemy-plugin >=0.4.3.0
    - polysemy-time
    - prometheus-client
    - prometheus-metrics-ghc
    - relude >=1.0.0.1
    - servant-lucid
    - servant-server
    - time
    - unix
    - unliftio
    - validation-selective
    - wai-extra
    - wai-middleware-prometheus
    - warp

executables:
  gitlab-ci-build-statuses-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-T
    dependencies:
      - gitlab-ci-build-statuses

tests:
  gitlab-ci-build-statuses-test:
    main: Spec.hs
    source-dirs: test
    default-extensions:
      - NoImplicitPrelude
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-T
    dependencies:
      - gitlab-ci-build-statuses
      - containers
      - hedgehog
      - hspec
      - hspec-hedgehog
      - katip
      - network-uri
      - path
      - polysemy >=1.7
      - polysemy-plugin >=0.4.3.0
      - relude >=1.0.0.1
      - validation-selective
