{
 "title": "Build Statuses",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "path",
    "query": {
     "query": "label_values(outgoing_http_requests_histogram_bucket, path)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(update_job_duration_histogram_bucket, tag)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "unhealthy pipelines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(build_pipelines_by_status_gauge{build_status=\"unhealthy\"})"
    }
   ]
  },
  {
   "title": "healthy pipelines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(build_pipelines_by_status_gauge{build_status=\"healthy\"})"
    }
   ]
  },
  {
   "title": "pipelines by status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(build_pipelines_by_status_gauge{build_status!~\"healthy|unhealthy\"}) by(build_status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "incoming requests for app",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_count{handler=\"app\"}[$__range]))"
    }
   ]
  },
  {
   "title": "request duration of outgoing requests combined",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(outgoing_http_requests_histogram_bucket[2m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(outgoing_http_requests_histogram_bucket[2m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(outgoing_http_requests_histogram_bucket[2m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.975, sum(rate(outgoing_http_requests_histogram_bucket[2m])) by (le))",
     "legendFormat": "p97.5"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(outgoing_http_requests_histogram_bucket[2m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "outgoing requests per path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(outgoing_http_requests_histogram_count[2m])) by(path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Duration of the update job ($job)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(update_job_duration_histogram_bucket[2m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(update_job_duration_histogram_bucket[2m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(update_job_duration_histogram_bucket[2m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.975, sum(rate(update_job_duration_histogram_bucket[2m])) by (le))",
     "legendFormat": "p97.5"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(update_job_duration_histogram_bucket[2m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "request duration of incoming requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, handler))",
     "legendFormat": "{{handler}} - p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, handler))",
     "legendFormat": "{{handler}} - p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, handler))",
     "legendFormat": "{{handler}} - p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, handler))",
     "legendFormat": "{{handler}} - p99"
    }
   ]
  },
  {
   "title": "incoming requests per handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count[2m])) by(path, handler)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Update job frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(update_job_duration_histogram_count[5m])) by (tag)",
     "legendFormat": "{{tag}} - 5m"
    },
    {
     "expr": "sum(increase(update_job_duration_histogram_count[15m])) by (tag)",
     "legendFormat": "{{tag}} - 15m"
    }
   ]
  },
  { "title": "outgoing requests per path", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "request duration outgoing requests - $path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "repeat": "path",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(outgoing_http_requests_histogram_bucket{path=~\"$path\"}[2m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(outgoing_http_requests_histogram_bucket{path=~\"$path\"}[2m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(outgoing_http_requests_histogram_bucket{path=~\"$path\"}[2m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.975, sum(rate(outgoing_http_requests_histogram_bucket{path=~\"$path\"}[2m])) by (le))",
     "legendFormat": "p97.5"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(outgoing_http_requests_histogram_bucket{path=~\"$path\"}[2m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Internals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{pod=~\"gitlab-ci-build-statuses-.*\", container=\"gitlab-ci-build-statuses\"}[1m])",
       "legendFormat": "container usage {{pod}}"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests_cpu_cores{pod=~\"gitlab-ci-build-statuses-.*\"})",
       "legendFormat": "container requests"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_cpu_cores{pod=~\"gitlab-ci-build-statuses-.*\"})",
       "legendFormat": "container limits"
      }
     ]
    },
    {
     "title": "Memory pod",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod=~\"gitlab-ci-build-statuses-.*\",container=\"gitlab-ci-build-statuses\"}",
       "legendFormat": "container usage {{pod}}"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests_memory_bytes{pod=~\"gitlab-ci-build-statuses-.*\"})",
       "legendFormat": "container requests"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_memory_bytes{pod=~\"gitlab-ci-build-statuses-.*\"})",
       "legendFormat": "container limits"
      }
     ]
    },
    {
     "title": "CPU throttling",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"gitlab-ci-build-statuses-.*\", container=\"gitlab-ci-build-statuses\"}[1m])",
       "legendFormat": "throttling {{pod}}"
      }
     ]
    },
    {
     "title": "GC runs",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(ghc_gcs_total[2m]))",
       "legendFormat": "GCs"
      },
      {
       "expr": "sum(increase(ghc_major_gcs_total[2m]))",
       "legendFormat": "major GCs"
      }
     ]
    },
    {
     "title": "GHC allocated bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(increase(ghc_allocated_bytes_total[2m]))"
      }
     ]
    }
   ]
  }
 ]
}