global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: builds
    scrape_interval: 5s
    static_configs:
      - targets:
          - gitlab-ci-build-statuses:8282
  - job_name: nodeexporter
    scrape_interval: 5s
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8081
  - job_name: grafana
    scrape_interval: 5s
    static_configs:
      - targets:
          - grafana:3000
