global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - 127.0.0.1:9090
  - job_name: builds
    scrape_interval: 5s
    static_configs:
      - targets:
          - 127.0.0.1:8282
  - job_name: nodeexporter
    scrape_interval: 5s
    static_configs:
      - targets:
          - 127.0.0.1:9100
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - 127.0.0.1:8080
  - job_name: grafana
    scrape_interval: 5s
    static_configs:
      - targets:
          - 127.0.0.1:3000
