name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/stack.yaml.lock','**/gitlab-ci-build-statuses.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.8.4'
          enable-stack: true
          stack-version: '2.5.1'

      - name: Install dependencies
        run: stack --no-terminal --install-ghc test --only-dependencies

      - name: Build executable
        run: stack build --system-ghc --test --copy-bins --local-bin-path .

      - uses: actions/upload-artifact@v2
        with:
          name: gitlab-ci-build-statuses-exe
          path: gitlab-ci-build-statuses-exe

#  docker:
#    name: Docker build & push
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: actions/download-artifact@v2
#        with:
#          name: gitlab-ci-build-statuses-exe
#
#      - uses: docker/setup-qemu-action@v1
#        name: Set up QEMU
#
#      - uses: docker/setup-buildx-action@v1
#        name: Set up Docker Buildx
#
#      - uses: docker/login-action@v1
#        name: Login to DockerHub
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: l7r7/gitlab-ci-build-statuses:latest
#
#      - name: Image digest
#        run: echo ${{ steps.docker_build.outputs.digest }}