name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.8.4' # Exact version of ghc to use
          enable-stack: true
          stack-version: '2.3.3'
      - run: stack build --system-ghc --copy-bins --local-bin-path .