name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: stack-cache

      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.8.4'
          enable-stack: true
          stack-version: '2.3.3'

      - name: Install dependencies
        run: stack --no-terminal --install-ghc test --only-dependencies

      - name: Build executable
        run: stack build --system-ghc --copy-bins --local-bin-path .

      - uses: actions/upload-artifact@v2
        with:
          name: service-executable
          path: gitlab-ci-build-statuses-exe

  docker:
    name: Docker build & push
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: service-executable

      - uses: mr-smithers-excellent/docker-build-push@v4
        name: Build & push Docker image
        with:
          image: l7r7/gitlab-ci-build-statuses
          tag: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}