name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2.1.4
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/stack.yaml.lock','**/gitlab-ci-build-statuses.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.8.4'
          enable-stack: true
          stack-version: '2.5.1'

      - name: Install dependencies
        run: stack --no-terminal --install-ghc test --only-dependencies

      - name: Build executable
        run: stack build --system-ghc --test --copy-bins --local-bin-path .

      - uses: actions/upload-artifact@v2
        with:
          name: gitlab-ci-build-statuses-exe
          path: gitlab-ci-build-statuses-exe
  
  markdown:
    name: Markdown lint
    runs-on: ubuntu-20.04
    steps:
      - name: MarkdownLint mdl Action
        uses: actionshub/markdownlint@2.0.2

  docker:
    name: Docker build & push
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: gitlab-ci-build-statuses-exe

      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx

      - uses: docker/login-action@v1
        name: Login to DockerHub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: l7r7/gitlab-ci-build-statuses
          tag-custom: latest
          tag-semver: |
            {{version}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
